// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class Account
{
    public int UId { get; set; }

    public string Username { get; set; }

    public string Pass { get; set; }

    public string Name { get; set; }
}