// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class Category1
{
    public int CateId { get; set; }

    public string Cname { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}