// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class Categor
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }
}