// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class DiscountCode
{
    public int DisCodId { get; set; }

    public string DisCod { get; set; }

    public int DisNum { get; set; }
}