// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public int? Rating { get; set; }

    public string Note { get; set; }

    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    public int? ProductId { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}