// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class Order
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public DateTime? OrderDate { get; set; }

    public decimal? TotalMoney { get; set; }

    public string Note { get; set; }

    public string Email { get; set; }

    public string Fullname { get; set; }

    public string Address { get; set; }

    public string Country { get; set; }

    public string PhoneNumber { get; set; }
}