// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class Product
{
    public int Id { get; set; }

    public int? CateId { get; set; }

    public string Name { get; set; }

    public string Size { get; set; }

    public decimal? Price { get; set; }

    public virtual Category1 Cate { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}