// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class Product1
{
    public int Id { get; set; }

    public int? CategoryId { get; set; }

    public string Title { get; set; }

    public decimal? Price { get; set; }

    public int? Quantity { get; set; }

    public int? Discount { get; set; }

    public string Description { get; set; }

    public int? Status { get; set; }

    public int? BrandId { get; set; }

    public string Image { get; set; }
}