// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthcareAppointment.Models.Models;

public partial class User1
{
    public string Username { get; set; }

    public string Password { get; set; }

    public int? Role { get; set; }
}